server:
  port: 8080

cloud:
  eureka-host: localhost
  processing-service-url: http://localhost:8090
  currency-service-url: http://localhost:8085

spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: currency
          uri: ${cloud.currency-service-url}
          predicates:
            - Path=/currency/**
        - id: processing
          uri: ${cloud.processing-service-url}
          predicates:
            - Path=/processing/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${cloud.eureka-host}:8761/eureka